# Which  of  the  following  statements  throw  NameError ?  (Home  work)
a = 25
print(a) # 25
del  a
#print(a) # NameError :  object  'a'  does  not  exist
print(eval("   'Ten'   ")) # Ten
#print(eval('Ten')) # NameError  :  object  Ten does  not  exist


'''
When  is  NameError  raised ?  ---   When  a  non-existing  object  is  accessed
'''